{% set name = "ccache" %}
{% set version = "4.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ccache/ccache/releases/download/v{{ version }}/ccache-{{ version }}.tar.gz
  sha256: 320d2b17d2f76393e5d4bb28c8dee5ca783248e9cd23dff0654694d60f8a4b62

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    # The test suite assumes GNU sed and find
    - sed
    - findutils  # [osx]
  host:
    - zstd

test:
  commands:
    - ccache --help
    - ccache --version

about:
  home: https://ccache.dev/
  license: GPL-3.0-only
  license_family: GPL
  license_file: GPL-3.0.txt
  summary: A compiler cache

  description: |
    ccache is a compiler cache. It speeds up recompilation by caching
    previous compilations and detecting when the same compilation is
    being done again. Supported languages are C, C++, Objective-C and Objective-C++.
  doc_url: https://ccache.dev/manual/latest.html
  dev_url: https://github.com/ccache/ccache

extra:
  recipe-maintainers:
    - edisongustavo
    - marcelotrevisani
