{% set name = "ccache" %}
{% set version = "4.8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ccache/ccache/releases/download/v{{ version }}/ccache-{{ version }}.tar.gz
  sha256: 75eef15b8b9da48db9c91e1d0ff58b3645fc70c0e4ca2ef1b6825a12f21f217d

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - pkg-config
    - ninja
    # The test suite assumes GNU sed and find
    - sed        # [not win]
    - findutils  # [osx]
  host:
    - libhiredis
    - zstd
    - ucrt  # [win]
  run:
    - ucrt  # [win]

test:
  commands:
    - ccache --help
    - ccache --version

about:
  home: https://ccache.dev/
  license: GPL-3.0-only
  license_family: GPL
  license_file: GPL-3.0.txt
  summary: A compiler cache

  description: |
    ccache is a compiler cache. It speeds up recompilation by caching
    previous compilations and detecting when the same compilation is
    being done again. Supported languages are C, C++, Objective-C and Objective-C++.
  doc_url: https://ccache.dev/manual/latest.html
  dev_url: https://github.com/ccache/ccache

extra:
  recipe-maintainers:
    - edisongustavo
    - marcelotrevisani
    - wolfv
