{% set name = "ccache" %}
{% set version = "3.7.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ccache/ccache/releases/download/v{{ version }}/ccache-{{ version }}.tar.gz
  sha256: d2abe88d4c283ce960e233583061127b156ffb027c6da3cf10770fc0c7244194
  patches: patch_test_suite.patch  # [osx]

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
  host:
    - zlib
    - xz
  run:
    - zlib

test:
  commands:
    - ccache --help
    - ccache --version

about:
  home: https://ccache.samba.org/
  license: GPL-3.0-only
  license_family: GPL
  license_file: GPL-3.0.txt
  summary: A compiler cache

  description: |
    ccache is a compiler cache. It speeds up recompilation by caching
    previous compilations and detecting when the same compilation is
    being done again. Supported languages are C, C++, Objective-C and Objective-C++.
  doc_url: https://ccache.samba.org/manual.html
  dev_url: https://github.com/ccache/ccache

extra:
  recipe-maintainers:
    - edisongustavo
    - marcelotrevisani
