{% set name = "ccache" %}
{% set version = "3.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ccache/ccache/releases/download/v{{ version }}/ccache-{{ version }}.tar.bz2
  sha256: 1c6501d5bd01952f5535c3f11ca774aedf4711e373a7bea7e0b1f487f0789b19

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - posix  # [win]
    - m2-automake-wrapper  # [win]
    - m2w64-toolchain  # [win]
    - m2-autoconf  # [win]
    - m2-libtool  # [win]
  host:
    - zlib
    - xz
  run:
    - zlib

test:
  commands:
    - ccache --help
    - ccache --version

about:
  home: https://ccache.samba.org/
  license: GPL-3.0
  license_family: GPL
  license_file: GPL-3.0.txt
  summary: 'A compiler cache'

  description: |
    ccache is a compiler cache. It speeds up recompilation by caching
    previous compilations and detecting when the same compilation is
    being done again. Supported languages are C, C++, Objective-C and Objective-C++.
  doc_url: https://ccache.samba.org/manual.html
  dev_url: https://github.com/ccache/ccache

extra:
  recipe-maintainers:
    - edisongustavo
    - marcelotrevisani
