{% set name = "ccache" %}
{% set version = "3.3.4" %}
{% set sha256 = "fa9d7f38367431bc86b19ad107d709ca7ecf1574fdacca01698bdf0a47cd8567" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.bz2
  url: https://www.samba.org/ftp/ccache/{{ name }}-{{ version }}.tar.bz2
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - zlib 1.2.*
    - xz 5.2.*
    - posix  # [win]
    - m2-automake-wrapper  # [win]
    - {{ native }}toolchain  # [win]
    - {{ posix }}automake  # [not win]
    - {{ posix }}autoconf
    - {{ posix }}libtool
  run:
    - zlib 1.2.*

test:
  commands:
    - ccache --help
    - ccache --version
    - which ccache

about:
  home: https://ccache.samba.org/
  license: GPL-3.0
  summary: 'a compiler cache'

  description: |
    ccache is a compiler cache. It speeds up recompilation by caching
    previous compilations and detecting when the same compilation is
    being done again. Supported languages are C, C++, Objective-C and Objective-C++.
  doc_url: https://ccache.samba.org/manual.html
  dev_url: https://github.com/ccache/ccache

extra:
  recipe-maintainers:
    - edisongustavo
