{% set name = "ccache" %}
{% set version = "4.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ccache/ccache/releases/download/v{{ version }}/ccache-{{ version }}.tar.gz
  sha256: 357a2ac55497b39ad6885c14b00cda6cf21d1851c6290f4288e62972665de417

build:
  number: 0
  skip: true  # [not win]

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}  # [unix]
    - {{ compiler('cxx') }}  # [unix]
    # TODO do this properly
    # - clang_win-64  # [win]
    - {{ compiler('m2w64_c') }}          # [win]
    - {{ compiler('m2w64_cxx') }}        # [win]
    - cmake
    - ninja
    # The test suite assumes GNU sed and find
    - sed        # [not win]
    - findutils  # [osx]
  host:
    - libhiredis
    - zstd

test:
  commands:
    - ccache --help
    - ccache --version

about:
  home: https://ccache.dev/
  license: GPL-3.0-only
  license_family: GPL
  license_file: GPL-3.0.txt
  summary: A compiler cache

  description: |
    ccache is a compiler cache. It speeds up recompilation by caching
    previous compilations and detecting when the same compilation is
    being done again. Supported languages are C, C++, Objective-C and Objective-C++.
  doc_url: https://ccache.dev/manual/latest.html
  dev_url: https://github.com/ccache/ccache

extra:
  recipe-maintainers:
    - edisongustavo
    - marcelotrevisani
