travis:
  secure:
    BINSTAR_TOKEN: U3mPeovSrChiERdRdVanhXa03/5kUIOgfT75q5xwNI2KKJFvoas7qLxGjRiiAjWWUn7q3topPliSUloOErVot460F0FfVPwKOANKlF/GtfplyyKwNPFNYDEDs8ziOKPC2JmX6U44Zn9t/9/xEyymT8sCePVsU6drb2JxjLqDGEZTmCRUD88N2xAlg2rujE/NJ9JxDr5pHHxH/cRRqkAFS5ufVaCpgdiVb2la85+ELkm9mV+/3JoI2sCgtVHM5EliWnnUWOqKSKIPDLb8oKxS6HvbtcJa7xnqdmzFiOGOqWD3YXIAjH+ufB0WeJ9rXQDFi4qNw5ktFZ7Suq3qZ8+z5D7iz3QrD+5F1C1MK4ce1Vj/VDBROyxIVWDGT9cO2CmEEzuOl9zgnboSpIp0kAPgZ4o/3OC30FW5q8OxglqmSSLFP++JRfTQsaVffoUE+IOMpgbyNDK5OW0GLCHnQmveCJ7UOoVXRxEMlJv10261I2Cwfd2CNSHTs/1uY+x8/9zBzbAiL5RQB1ssa9Z8wGQv1VdtSFLL8XIWmhXcALPpC6j8+0AFYHH+fNf81iKAFi6bZFDgTa+exoXGPAi4KLvOziqrhBN4Ch8S4FPtNHW+TqgTwV/ClVH0hIXcqfcdDKy04zdsiaoMIQvVjCcmcq29PpGAdNajelRq6eWzvQxs1Gc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider: {linux_aarch64: default, linux_ppc64le: default}
conda_forge_output_validation: true
